In [3]:
import numpy as np

# 0-D Array (Scalar)
scalar_array = np.array(42)
print(f"0-D Array (Scalar):\n{scalar_array}")

# 1-D Array (Vector)
vector_array = np.array([1, 2, 3, 4, 5])
print(f"1-D Array (Vector):\n{vector_array}\n")

# 2-D Array (Matrix)
matrix_array = np.array([[10, 11, 12], [13, 14, 15]])
print(f"2-D Array (Matrix):\n{matrix_array}\n")


0-D Array (Scalar):
42
1-D Array (Vector):
[1 2 3 4 5]

2-D Array (Matrix):
[[10 11 12]
 [13 14 15]]



In [4]:
# Creating random arrays
random_array_3d = np.random.rand(2, 2, 2)
print(f"3D Array with Random Numbers (2x2x2):\n{random_array_3d}")


3D Array with Random Numbers (2x2x2):
[[[0.33788873 0.3749721 ]
  [0.18371065 0.9233728 ]]

 [[0.18579639 0.06138339]
  [0.59288376 0.92546307]]]
